### ISSUE TITLE
Use DIR_DELIM instead of assuming slash as directory separator

### ISSUE THREAD

**Issue by ghost** [berengma/interkom#1]
https://github.com/berengma/interkom/blob/3a157cce264407ef86d20e02bc0174ba8835131b/init.lua#L14

Better use `DIR_DELIM` here: minetest.get_worldpath()..DIR_DELIM.."Lilly"

... and who's Lilly?

**Comment by berengma** [comment]
never heard about DIR_DELIM
Will try that maybe.

Who Lilly is ? That is the big question of Lilly in the valley.
