### ISSUE TITLE
Use minetest.settings:get() instead of hardcoding options in code

### ISSUE THREAD

**Issue by ghost** [berengma/interkom#2]
You should not hardcode values to your code because it makes updates for the users harder because they will lose all changes to the options or need to manually merge their changes.

https://github.com/berengma/interkom/blob/3a157cce264407ef86d20e02bc0174ba8835131b/settings.lua#L4-L6

This could be written as

```lua
interkom.name        = minetest.settings:get("interkom_name") or "Gundul's" -- enter a unique Servername 
interkom.intervall   = minetest.settings:get("interkom_interval") or 3      -- how many seconds between each check for actionqueue 
interkom.blacklistTO = minetest.settings:get("interkom_blacklistTO") or 60  -- how many seconds to answer until people get on blacklist 
```

When adding a `settingtypes.txt` to your mod you can provide the users with advanced settings.

```
interkom_name (Unique server name) string Gundul's
interkom_interval (Sseconds between each check) int 3
interkom_blacklistTO (Seconds to answer until people get on blacklist) int 60
```

The settingtypes functionality is documented [here](https://dev.minetest.net/settingtypes.txt).

**Comment by berengma** [comment]
Thanks I know about settingtypes. This is itentionally. Not too much convenience. This mod is very wip and not made for beginners.
